export const PATIENTS = {
	GET: 'GET_PATIENTS',
	SET: 'SET_PATIENTS',
	ADD: 'ADD_PATIENTS',
	REMOVE: 'REMOVE_PATIENTS',
	UPDATE: 'UPDATE_PATIENTS',
	ERROR: 'ERROR_PATIENTS'
};

export const OUTPUTS = {
	GET: 'GET_OUTPUTS',
	SET: 'SET_OUTPUTS',
	ADD: 'ADD_OUTPUTS',
	REMOVE: 'REMOVE_OUTPUTS',
	UPDATE: 'UPDATE_OUTPUTS',
	ERROR: 'ERROR_OUTPUTS'
};

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';