export const ROOMS = {
	GET_ROOMS: 'GET_ROOMS',
	ADD_ROOM: 'ADD_ROOMS',
	REMOVE: 'REMOVE_ROOMS',
	UPDATE: 'UPDATE_ROOMS',
	ORDER_CHANGE: 'ROOMS_ORDER_CHANGE'
};

export const ROOM_TYPES = {
	GET: 'GET_ROOM_TYPES',
	ADD: 'ADD_ROOM_TYPES',
	REMOVE: 'REMOVE_ROOM_TYPES',
	UPDATE: 'UPDATE_ROOM_TYPES',
	ORDER_CHANGE: 'ROOM_TYPES_ORDER_CHANGE'
};

export const PHASES = {
	GET: 'GET_PHASES',
	ADD: 'ADD_PHASES',
	REMOVE: 'REMOVE_PHASES',
	UPDATE: 'UPDATE_PHASES'
};

export const PRODUCTS = {
	GET: 'GET_PRODUCTS',
	ADD: 'ADD_PRODUCTS',
	REMOVE: 'REMOVE_PRODUCTS',
	UPDATE: 'UPDATE_PRODUCTS',
	INIT: 'INIT_PRODUCTS',
	CHANGE: 'CHANGE_PRODUCTS'
};

export const TUNE_PRODUCTS = {
	GET: 'GET_FINE_PRODUCTS',
	ADD: 'ADD_FINE_PRODUCTS',
	REMOVE: 'REMOVE_FINE_PRODUCTS',
	UPDATE: 'UPDATE_FINE_PRODUCTS'
};

export const STAGES = {
	INIT: 'INIT_STAGES',
	GET: 'GET_STAGES',
	ADD: 'ADD_STAGES',
	REMOVE: 'REMOVE_STAGES',
	UPDATE: 'UPDATE_STAGES',
	DELETE_PRODUCTS: 'DELETE_PRODUCTS_FROM_STAGE',
	UPDATE_PRODUCTS: 'UPDATE_PRODUCTS_FROM_STAGE',
	ADD_PRODUCTS: 'ADD_PRODUCTS_TO_STAGE',
	CHANGE_PRODUCT_ORDER: 'CHANGE_PRODUCT_ORDER_STAGE'
};